### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by vgturtle127** [tj90241/cen64#14]
Alright, so I tried the latest builds available on the cen64.com website because I figured they would be more reliable then if I tried to compile them myself.

When I launch the debugger, it works fine. The debugger comes up.

When I launch the other builds (all 64-bit by the way), I get an error message typical of having outdated runtimes.

---------------------------
cen64-win64-[cpu instruction]-latest.exe - Application Error
---------------------------
The application was unable to start correctly (0xc000007b). Click OK to close the application. 
---------------------------
OK   
---------------------------

I had to put the OpenAL32.dll in the directory to get it to get this far, could I have a different version then I am supposed to have?

I don't know, I've tried everything I can think of.

Any ideas would be great.

After installing the latest OpenAL installer, now it just doesn't open. Any thoughts? I have tried running from a command prompt as well as just running the executable...

I am running 64-bit Windows 7 Ultimate SP1 (fully updated).

This may be worth mentioning, I have all the Visual C++ runtimes installed (32-bit and 64-bit).

**Comment by tj90241** [comment]
I built them on Windows 8, FWIW, but I don't think the runtimes should really matter since it should use a statically linked GNU libc IIRC. I have a Windows 7 SP1 system, so I'll try it on that when I get a chance and report back.

**Comment by tj90241** [comment]
Also, FWIW, CEN64 was linked against openal-soft, not the closed-source OpenAL. I imagine (or at least hope) the ABIs are the same between the two, but it might be worth trying that as well.

All I've had to do, however, is just put the exe and dll in the same directory...

**Comment by vgturtle127** [comment]
OK, I will try OpenAL-soft and report back.

IIRC, the API's are compatible, but I think OpenAL-soft may have differences in compatibility depending on the application. Good move going with OpenAL-soft and not the closed-source version. Better for the future.

**Comment by tj90241** [comment]
Yeah I noticed that just the other day.

I guess I couldn't be bothered enough to deal with it right now as it takes away what little precious developer time I seem to be finding as of late. If you are interested in looking into it, I am most grateful.

**Comment by vgturtle127** [comment]
Well, I tried OpenAL-soft, but the DLL isn't the correct name. I renamed it and it still doesn't work. I tried all four versions and the debugger version.

I have tried both double clicking on the executable and running them from a command prompt.

I'm not sure what I'm doing wrong, but I have done everything I can think of. :disappointed: 

I uploaded all the files on the site to VirusTotal and Jotti's malware scan. They are all clean.

I also scanned the website with many popular web scanners. They all checked out as well.

I also went to website reputation sites, and they had the same thing to say. The people who visited had nothing more than good things to say about the site. :smiley: 

So I'm going to contact the Google safe browsing team and find out why they blacklisted the site. I will report back any findings.

**Comment by vgturtle127** [comment]
I found the advisory, it looks like they had this to say about it:

![screenshot 29](https://cloud.githubusercontent.com/assets/3183676/8739283/5d917b88-2bff-11e5-94c1-30de53f91fd9.png)

Do you have a Google account?

**Comment by tj90241** [comment]
I don't think you don't have enough tabs open in that browser of yours. :smile:

I recently migrated the website to a different VM, so I wonder if Google is flagging it on the basis that it looks compromised.

I don't have an AdSense/Webmaster account, but maybe it's time to get one.

Sorry for not checking on the Win7 runtime issue yet...

**Comment by tj90241** [comment]
I signed up for a Webmaster account so hopefully it gets cleared up soon.

**Comment by vgturtle127** [comment]
Alright. I managed to contact Mozilla and they cleared up that issue. Apparently, somebody on the team added your domain due to the fact that multiple Firefox users had reported issues with software on the site, who then afterwards downloaded "working" versions off of the internet. These were fake versions of CEN64 (although the executables had Project64 1.6 in them for some reason :confused: ).

Weird, but it's cleared up now. :open_mouth: 

In regards to Internet Explorer, I sent a report to Microsoft explaining that the files are clean, the website is secure, and you have control over the entire site. So even if there was a problem, you would be able to handle it. They said they would white list the site again. So hopefully that will be resolved soon as well.

> I don't think you don't have enough tabs open in that browser of yours. :smile: 

Funnily enough, most of those are GitHub. Some are various emulation Wikis, and a few YouTube videos of emulation or console hacking stuff, but mostly GitHub. I just recently started contributing to basically every emulator ever, so my web browser has looked like that for a week and a half now. :laughing: 

The downside is managing them is hard, so I should probably close a few. :smile:

**Comment by tj90241** [comment]
![banjo](https://cloud.githubusercontent.com/assets/2336200/8761808/628dca8a-2d33-11e5-887e-5f71f5af9202.PNG)

Unvirtualized, stock, up-to-date Windows 7 machine. Just about the only thing I have installed on it is Chrome, Steam, and what you see on my desktop (no developer tools or libraries of any sort).

So I'm thinking (hoping?) it's a localized problem?

**Comment by tj90241** [comment]
Some other thoughts?

- Do you have a graphics driver that supports OpenGL 2.x?
- Have you tried installing .NET framework redistributables?

Literally all I have on my machine:
![capture](https://cloud.githubusercontent.com/assets/2336200/8761867/41bb0082-2d35-11e5-9021-7c10afbb2261.PNG)

**Comment by vgturtle127** [comment]
Well, I have Windows and the .NET framework fully up to date, so I don't think that's it.

My graphics driver supports OpenGL up to version 4.4. That is also probably not it.

I'm running an Nvidia GTX 750Ti if that helps at all.

Let me try re-downloading them from the website.

**Comment by vgturtle127** [comment]
I tried re-downloading them.

Just to be sure I am doing everything correctly, how did you run your Banjo Kazooie ROM?

**Comment by tj90241** [comment]
I have an older nVIDIA card, and the updates rule out the software issue...

Here's the md5sum of the two files I'm using:
4921d5f2165dee6e2496f4388c4c81da  pifrom.bin
b29599651a13f681c9923d69354bf4a3  banjo.z64

All you should have to do is open a cmd.exe window and type:
cen64.exe pifrom.bin banjo.z64

(making sure that OpenAL32.dll is in the same directory as your cen64.exe).

**Comment by vgturtle127** [comment]
My MD5 sum is the same for pifrom.bin, and I ran the command prompt exactly like that and it still won't run the darn ROM :weary: 

If it helps I am running some public domain ROMs? The one I tried was called N64 Stars Demo. I also tried Absolutely Crap Intro 2 by LEM, Liner v1.00, and Rotating Demo USA.

I should also mention they are .v64 files. I'm not sure if you have support for all the N64 file types or not. I can't remember if I was reading about file support in CEN64 in your code comments recently or not. It may have been another emulator.

**Comment by tj90241** [comment]
I only support one N64 file type: the native one. Non-bytewapped, little endian.

The first 4 bytes of the image should be:
80 37 12 40

Exactly in that order.

**Comment by vgturtle127** [comment]
37 80 40 12  is my order. :cry: 

Is there a way to convert from byte-swapped to non-byteswapped? Actually, isn't n64tool a converter as well, or am I thinking of something else?

**Comment by tj90241** [comment]
Yep, that's your problem. Closing the issue. :+1: 

No, N64Tool is not a converter. You're thinking of something else.

**Comment by vgturtle127** [comment]
There is one problem, I byte-swapped the ROM and it still doesn't work! :disappointed: 

Again, I did just as you did. Does your emulator require certain file extensions perhaps?

**Comment by tj90241** [comment]
No, file extension doesn't matter.

What's the first 4 bytes of the image now?

**Comment by vgturtle127** [comment]
80 37 12 40 is the first 4 bytes.

I wish there were better documentation on the differences between .v64, .z64, .n64, etc. :disappointed: 

It doesn't even open anything, it just doesn't open. :disappointed: 

Maybe there is a problem with ROM loading or something? Maybe certain characters throw it off or something? I don't know, I'm kind of throwing stuff out there since I have never had this problem before, and the code looks fine as far as I can tell...

**Comment by tj90241** [comment]
I wonder if this has something to do with it:

>> After installing the latest OpenAL installer, now it just doesn't open. Any thoughts? I have tried running from a command prompt as well as just running the executable...

You still have OpenAL32.dll (from downloads.cen64.com) in the same directory as the exe?

**Comment by vgturtle127** [comment]
Yeah.
