### ISSUE TITLE
Banjo Kazooie doesn't work

### ISSUE THREAD

**Issue by ghost** [tj90241/cen64#15]
Don't know if this is the place to report an issue or not, but Banjo Kazooie plays the opening sound and the screen is supposed to open from the center, but it just stays this way. No logs or anything.

![1](https://cloud.githubusercontent.com/assets/13189357/8610608/638f290e-2682-11e5-8d1a-5a707178c63b.jpg)
![2](https://cloud.githubusercontent.com/assets/13189357/8610610/64d972b0-2682-11e5-95b2-8e0d513ace41.jpg)

Is there a way to debug or find out further info about CEN64 and this game?

**Comment by tj90241** [comment]
It's fixed in the Windows builds, but the "build bot" of sorts is having issues with the Windows builds hosted on http://downloads.cen64.com.

So I have to manually do a Windows build of the latest binary and push it first, sorry.

**Comment by tj90241** [comment]
New Windows builds pushed and verified working with this game. Closing the issue.
