### ISSUE TITLE
MAME 0.163 PIF ROM fails with "Unimplemented instruction: INVALID [0x00000000] @ 0x00000000"

### ISSUE THREAD

**Issue by andlabs** [tj90241/cen64#16]
I'm not sure if you already know this or not but with the current master (commit 98d3ae952cf315b8456abff54fa9d96d388b0465) built on Linux, playing any game with an unmodified MAME-compatible PIF ROM (pifdata.bin, sha1sum `9174eadc0f0ea2654c95fd941406ab46b9dc9bdd`) results in

    Unimplemented instruction: INVALID [0x00000000] @ 0x00000000

being printed repeatedly to the terminal, with games not booting.

Byte-swapping the PIF ROM gets rid of the errors, but games still won't boot.

I tested this with both Super Mario 64 and Ocarina of Time, both byte-swapped and not; cen64 rejected the byte-swapped versions, so that part still works...

This is Ubuntu GNOME 15.10 64-bit on an AMD A6-6310 APU with AMD Radeon R4 Graphics CPU and mesa for graphics. Build was done with `mkdir _build; cd _build; cmake ..; make`. Execution was done by `cd`ing into the directory with the ROMs and running cen64 via absolute path.

Thanks.

**Comment by tj90241** [comment]
master won't run commercial carts because it doesn't yet have an RDP.

You need to checkout angrylion-rdp in order to run those.

**Comment by tj90241** [comment]
Assuming that fixed it, closing.

**Comment by andlabs** [comment]
Yeah, that clears up the situation. Sorry for the delayed response. Thanks!
