### ISSUE TITLE
Fails to build with clang

### ISSUE THREAD

**Issue by beannaich** [tj90241/cen64#18]
I just built the project with GCC, all worked fine, and I got my CEN64 binary. However, if I run `$ make CC=clang` then the build fails during linking, with complaints about unresolved references. I tried attaching the build log as a file, but apparently you can only do that if you have write access to the repo. So [here](http://pastebin.com/Ujjj6hMG) is a link instead. This was with the HEAD of the `angrylion-rdp` branch.

**Comment by tj90241** [comment]
Fixed in 2ff54c5, please confirm and close, thanks.

**Comment by beannaich** [comment]
This has indeed been fixed!
