### ISSUE TITLE
Old build from website works OK but not my self compiled ones

### ISSUE THREAD

**Issue by sheepdestroyer** [tj90241/cen64#27]
I am on Fedora 23 x64 with an Intel Sandybridge. I tried building from SS2 to AVX with same results. I just get a black screen and a lot of these :
````
./cen64 pifdata.bin Super\ Mario\ 64\ \(U\)\ \[\!\].z64 
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
Unimplemented instruction: INVALID [0x00000000] @ 0x00000000
````

**Comment by sheepdestroyer** [comment]
Just saw a closed issue with similar errors and recommendation to try branch angrylion-rdp. I did but got same errors.

**Comment by tj90241** [comment]
That is debug output -- build with CMAKE_BUILD_TYPE=Release.

Also a good idea to build with VR4300_BUSY_WAIT_DETECTION=ON.

But, yes, please build with angrylion-rdp as well.

**Comment by sheepdestroyer** [comment]
Thanks, works great.
