### ISSUE TITLE
cen64-libretro (Suggestion)

### ISSUE THREAD

**Issue by orbea** [tj90241/cen64#43]
Hi,

I am wondering if you have considered porting your cen64 emulator over to the libretro api before? It may be more work at first, but eventually would free up your time from working on any interface and frontends to being able to dedicate your time to solely to working on the core emulator. Additionally it could make it easier for any libretro developers to contribute to cen64 or vica versa and would attract potentially far more users / bug testers.

https://github.com/libretro

Thanks for considering at least. :)

**Comment by tj90241** [comment]
Right now, CEN64 has a very small contributor base, pretty poor compatibility, and low performance. I'm investing a lot of time into bringing the emulator up to speed, and don't have any to spare for a libretro port at the time being. That being said, if somebody wants to work on a libretro port themselves, I am more than willing to give pointers.

**Comment by orbea** [comment]
Thank you for taking the time to reply. I can understand your position. Still I think it is something to consider in time when you feel CEN64 is more up to speed. With cooperation I think everyone could benefit. :)
