### ISSUE TITLE
welcome.z64 is wrongly colorful

### ISSUE THREAD

**Issue by jkbenaim** [tj90241/cen64#44]
[welcome.z64](https://jrra.zone/p/welcome.z64) is a ROM which displays a short, live-action video. cen64 can run this ROM, but the video output is wrong. The display is filled with block of primary colors:

![selectric](https://cloud.githubusercontent.com/assets/2214896/16360661/b7b09b2a-3b3b-11e6-8839-cdb2a8667556.png)

The picture should look something like this (taken from the source video):

![selectric2](https://cloud.githubusercontent.com/assets/2214896/16360734/0c4c28c2-3b3f-11e6-92d2-e1e1bf31e990.jpg)

**Comment by tj90241** [comment]
The video ucode is buggy, I knew about this one. :)

I think a lot of these bugs are stemming from one of the RSP loads or stores not being right in some edge case, but I can't say for certain because I really haven't looked too deeply into it.

**Comment by tj90241** [comment]
Fixed.
