### ISSUE TITLE
Pokemon Puzzle League doesn't boot.

### ISSUE THREAD

**Issue by lukestrong** [tj90241/cen64#46]
Hey, I'm not sure if you want these kinds of reports at the moment due to this emulator appearing to be relatively early in development, but so far this has been the only game I've tried that hasn't been able to start.
The emulator just shows a black screen without any audio with every version of cen64 I've tried (including the latest commit).

**Comment by GPDP2** [comment]
Mupen64Plus actually has the exact same issue. It's the only other N64 emulator I know of that cannot play this game. According to Richard42, it may be an SP interrupt issue on their end. Who knows if that is also the case here, but can't hurt to check.

**Comment by LegendOfDragoon** [comment]
Possibly something with VI emulation. In particular the current_line_reg.

**Comment by tj90241** [comment]
I haven't personally ever tried to run this ROM. My testing set is, admittedly, quite small.

@LegendOfDragoon thanks, I will look at the VI emulation.

**Comment by tj90241** [comment]
Works now.
