### ISSUE TITLE
[Super Mario 64] Mario's power meter looks wrong

### ISSUE THREAD

**Issue by jkbenaim** [tj90241/cen64#51]
In the angrylion-rdp-sse branch, Mario's power meter looks wrong: the bottom half is incorrectly shown as a copy of the top half. git bisect fingered 72ce1e0804954ff8b8da18a485e4af69bcbb4c34 as the guilty commit.

![mario64 gfx glitch](https://cloud.githubusercontent.com/assets/2214896/20026854/dde8244c-a2d9-11e6-843b-12f3c58ce9ce.png)

**Comment by LegendOfDragoon** [comment]
I made a pull request that might fix this issue.

**Comment by tj90241** [comment]
Fixed in #52
