### ISSUE TITLE
CEN64 Doesn't Open

### ISSUE THREAD

**Issue by tbmny** [tj90241/cen64#54]
When attempting to open CEN64 with openAL32.dll from the CEN64 website downloaded, CEN64 still does not open.

**Comment by tj90241** [comment]
More info needed. How are you running it? You can't just double-click it -- you need to run it from the command line and give the program some arguments.

If this all sounds foreign, you might want to look into using CEN64-Qt.

**Comment by tbmny** [comment]
I'm so stupid. I didn't know that there was no GUI for this one. I am familiar with running programs through a command line. Anyway, thanks for the help. Looking forward to the progress of this emulator.
