### ISSUE TITLE
Unknown CIC Type with ROM that works on console

### ISSUE THREAD

**Issue by JimmJamm** [tj90241/cen64#55]
I compiled the nu5 example from the development kit. It works on hardware with an Everdrive but if I try to run it in Cen64 I get the unknown CIC type error. The output of the compilation is a .n64 file but I checked and it's not actually byte-swapped. Would it be a legal issue to upload the rom here?

**Comment by tj90241** [comment]
Nope, totally not legal. But, we can resolve this through other means.

tyler@green:~$ hexdump -n 4 /home/tyler/projects/cen64-old/data/zelda.z64 
0000000 3780 4012                              
0000004

Can you print the first four bytes of the file and report back? Assuming the devkit is configured to use the same PI_BSB_DOM1_LAT_REG as most commercial carts (which it should), the output should be the same as above.

**Comment by JimmJamm** [comment]
I'll close this and put the solution here for future readers

1) extend the rom past 1MB, 2) replace the ipl3 area (from 40h to FFFh) with same from mario64, 3) recalculate crcs
