### ISSUE TITLE
Question -  SIMD extension dection

### ISSUE THREAD

**Issue by Krakn** [tj90241/cen64#56]
Is there any reason older SIMD extensions are preferred to newer ones?

Currently:

```
    if (${CEN64_ARCH_SUPPORT} MATCHES "SSE2")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse2")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSSE3")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mssse3")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSE3")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse3")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSE4.1")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse4")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "AVX")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx")
    endif ()
```

As opposed to:

```
    if (${CEN64_ARCH_SUPPORT} MATCHES "AVX")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mavx")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSE4.1")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse4")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSSE3")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mssse3")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSE3")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse3")
    elseif (${CEN64_ARCH_SUPPORT} MATCHES "SSSE2")
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -msse2")
    endif ()
```

**Comment by tj90241** [comment]
When proper support for IA-32 is added, the last elseif can be changed to an else and voila: -msse2 if you don't support anything else (which is pretty much required right now).

The order of the flags here doesn't matter as it stands...

**Comment by mikeryan** [comment]
It matters insofar as if you have a recent CPU, unless you're savvy enough to check cmake flags you will not be using best optimizations.

**Comment by tj90241** [comment]
The default (i.e., CEN64_ARCH_SUPPORT is not defined) means -msse2 gets selected. And x86_64 implementations are guaranteed to support SSE2. So unless you're manually touching things, it'll work out of the box.

**Comment by Krakn** [comment]
@tj90241 Ah, I'm not too savvy with cmake, and thought it was doing some fancy streaming SIMD extension detection. I had done some playing around with another branch and forgot to reset my CMakeCache.txt file...

Thanks for the explanation!
