### ISSUE TITLE
Build failure due to is_viewer

### ISSUE THREAD

**Issue by J-128** [tj90241/cen64#59]
OS: Linux Sabayon, X64

When I try to *make*, I get the following output: (I always use -j4. It makes Make make faster :smile:)

```
$ make -j4
[  1%] Linking C executable cen64
CMakeFiles/cen64.dir/pi/is_viewer.c.o: In function `is_viewer_init':
/home/user/misc/Other/Other/cen64/pi/is_viewer.c:21: undefined reference to `libiconv_open'
CMakeFiles/cen64.dir/pi/is_viewer.c.o: In function `write_is_viewer':
/home/user/misc/Other/Other/cen64/pi/is_viewer.c:62: undefined reference to `libiconv'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/cen64.dir/build.make:1814: cen64] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/cen64.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by Krakn** [comment]
Do you have libiconv installed?

**Comment by J-128** [comment]
@Krakn Yes, I do.

**Comment by Krakn** [comment]
Which version?

**Comment by J-128** [comment]
Libiconv 0-r2~0 according to my package manager.
If it helps, the description reads "Virtual for the GNU conversion library"

I also have Iconv 0.4.1.3 installed.

Hope this helps.

**Comment by mikeryan** [comment]
Fetch master, blow away your build directory, and rerun cmake. See if that last commit solves your problem.

**Comment by J-128** [comment]
Great, problem fixed! :smile:
Thanks a lot!
