### ISSUE TITLE
Compiling cen64 ?

### ISSUE THREAD

**Issue by azoreseuropa** [tj90241/cen64#61]
Curious.. No compiling from your source ? Can't find it.

**Comment by hcorion** [comment]
Just use cmake.
(asumming linux or mac)
`mkdir build ; cd build ; cmake ../`

**Comment by azoreseuropa** [comment]
git clone https://github.com/tj90241/cen64.git
mkdir build
cd build
cmake ../ (something is missing here)
make

Can you fill it in ? Something is missing.

**Comment by hcorion** [comment]
just `cmake ../` should work

**Comment by azoreseuropa** [comment]
Nope. I got an error:

CMake Error: The source directory "/Users" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by mikeryan** [comment]
cd cen64
mkdir build
cd build
cmake ../ (something is missing here)
make

**Comment by azoreseuropa** [comment]
Yeah... cmake ../ something is missing here definitely.

**Comment by hcorion** [comment]
Oh, that's because you need to cd into the directory you cloned cen64 into.
So if you cloned cen64 at `~/cen64` then you need to cd into that directory, before running the command

**Comment by azoreseuropa** [comment]
Please write completely complete so I can get to it. I had compiled few emulators. I want to write it down for this one too. :)

**Comment by hcorion** [comment]
Ok, 
```
git clone https://github.com/tj90241/cen64.git
cd cen64
mkdir build
cd build
cmake ../
make
```

**Comment by azoreseuropa** [comment]
Okay.. Now I got this error after type "make":
Scanning dependencies of target cen64
[  1%] Building C object CMakeFiles/cen64.dir/ai/context.c.o
[  2%] Building C object CMakeFiles/cen64.dir/ai/controller.c.o
[  4%] Building C object CMakeFiles/cen64.dir/arch/x86_64/tlb/tlb.c.o
[  5%] Building C object CMakeFiles/cen64.dir/arch/x86_64/rsp/vrcpsq.c.o
[  7%] Building C object CMakeFiles/cen64.dir/arch/x86_64/rsp/vmov.c.o
[  8%] Building C object CMakeFiles/cen64.dir/arch/x86_64/rsp/vdivh.c.o
[ 10%] Building C object CMakeFiles/cen64.dir/arch/x86_64/rsp/rsp.c.o
/Users/azoreseuropa/cen64/arch/x86_64/rsp/rsp.c:105:35: warning: unused variable
      'srl_b2l_keys' [-Wunused-const-variable]
cen64_align(static const uint16_t srl_b2l_keys[16][8], CACHE_LINE_SIZE) = {
                                  ^
1 warning generated.
[ 11%] Building C object CMakeFiles/cen64.dir/arch/x86_64/rsp/vrsq.c.o
[ 13%] Building C object CMakeFiles/cen64.dir/bus/controller.c.o
In file included from /Users/name/cen64/bus/controller.c:24:
In file included from /Users/name/cen64/vi/controller.h:14:
/Users/name/cen64/os/x11/gl_common.h:14:10: fatal error: 'GL/gl.h' file
      not found
#include <GL/gl.h>
         ^
1 error generated.
make[2]: *** [CMakeFiles/cen64.dir/bus/controller.c.o] Error 1
make[1]: *** [CMakeFiles/cen64.dir/all] Error 2
make: *** [all] Error 2

**Comment by hcorion** [comment]
Hmm, I guess cen64 doesn't support MacOS at the moment. What you can do is edit that line to say 
`#include <OpenGL/gl3.h>`
and the next line to say 
`#include <OpenGL/glx.h>`

**Comment by hcorion** [comment]
You could also try installing XQuartz.

**Comment by azoreseuropa** [comment]
I dont know how to edit it.

And I already have XQuartz. ^_^

**Comment by hcorion** [comment]
`cd /Users/name/cen64/os/x11 ; open ./gl_common.h`

**Comment by azoreseuropa** [comment]
Then what ? or should I wait for next better compile to do this ??

**Comment by azoreseuropa** [comment]
Please let me know  if I am ready to compile it now without edit it ? :)

**Comment by hcorion** [comment]
@azoreseuropa 
It should work now, if you `cd` into `cen64` then `git pull` it will get the latest changes.
Then if you just follow previous instructions it should build and work fine.

**Comment by azoreseuropa** [comment]
git clone https://github.com/tj90241/cen64.git
cd cen64
mkdir build
cd build
cmake ../
make

Right ??

But I got a feeling that cmake ../ (something is missing) unless you can make some change from my list here. Thanks.

**Comment by hcorion** [comment]
Yes. Can you confirm that works. Nothing is missing

**Comment by azoreseuropa** [comment]
Yes, compiling is working now. What about GUI ? I think I saw it is only type in terminal (Mac) and command line (windows) right ? I want to test it in terminal just in case but what should I type it ? GUI is mostly prefer but is there a way I can compile for GUI to run this emulator ?

**Comment by hcorion** [comment]
GUI is in a separate project, over here: https://github.com/dh4/cen64-qt

**Comment by azoreseuropa** [comment]
I can't find cen64 emulator after compiled it. Where ?

**Comment by hcorion** [comment]
It's at /Users/name/cen64/build/ it's cen64, you can run it by using `./cen64` after make

**Comment by azoreseuropa** [comment]
I don't understand by using ./cen64 after make. What do you mean ?

I found it and I move it to cen64 folder at download section and there is cen64-qt in Cen64 folder as well and click cen64-qt and click File>ROMS>Super Mario 64.n64 and I got this error:

CEN64 executable not found.

**Comment by hcorion** [comment]
That's because you need to set the location of the cen64 executable, it should be somewhere in the cen64-qt settings, you want to set it to /Users/name/cen64/build/cen64

**Comment by azoreseuropa** [comment]
Yeah, I edited it already. Read above for XQuartz pop up.

**Comment by hcorion** [comment]
Yeah, Xquartz popup is normal, speed should be slow, this emulator is very accurate. Could you close the bug report?

**Comment by azoreseuropa** [comment]
Good. I thought it is just me about Xquartz. Anyway, I am aware of your early development and speed should be slow. 

Anyway..

How do I close the bug report ?

**Comment by J-128** [comment]
You click the 'Close issue' button near the bottom of the page.

**Comment by azoreseuropa** [comment]
Thank you, J-128

But before I do that.. What Cen64 version is this that I already compiled ? :)

**Comment by hcorion** [comment]
The very latest, it doesn't have a version number at this point in time.

**Comment by azoreseuropa** [comment]
Alright. Thanks again! Closed now.
