### ISSUE TITLE
new syntax or broken build bot builds

### ISSUE THREAD

**Issue by AriaHiro** [tj90241/cen64#63]
it seems I'm no longer able to launch the latest build bot windows build through the command line or front end. I'm going to test on ubuntu later.

**Comment by Siilwyn** [comment]
Doesn't run on Ubuntu 16.04 either.

**Comment by tj90241** [comment]
I imagine it's because you're running the developer/new/unstable/not usable version and not the "stable" version. How big is the binary? If it's less than 100kb, it's not really intended for public consumption.

The website does not really make this clear, so mea culpa.

**Comment by AriaHiro** [comment]
Thanks for the quick responses, and yes I made the mistake of using that sub 100kb version. I also trust that the wait will be worth it.

**Comment by tj90241** [comment]
There is a buildbot for the current stable version, but the Windows builds have been broken since this commit: https://github.com/tj90241/cen64/commit/8d0e7bb627b91f4d592ebd2a7e3d87cf580cdb32

https://github-buildbot.cen64.com/builders

**Comment by AriaHiro** [comment]
Ah, thanks for the info, I got a functional build to pass the time.

**Comment by Siilwyn** [comment]
Yes thanks for the info. Unfortunately I still don't understand where to get a functional build from. :/
I assumed it would be by going to a successful build like [this page](https://github-buildbot.cen64.com/builders/debian-gnu_linux-x86_64-gcc-final/builds/5) but I don't see any way to download the build.

**Comment by AriaHiro** [comment]
@Siilwyn I just used the code right before the build bot crashed got the dependencies cmake pointed too and it worked for me. btw visual studio refuses to build but I don't think cen64 was designed for that.

**Comment by Siilwyn** [comment]
Ah okay I was hoping for a pre-made build, I have never build a C project.
