### ISSUE TITLE
cen64 and cen64-Qt for mac and maybe windows too ?? bug?

### ISSUE THREAD

**Issue by azoreseuropa** [tj90241/cen64#65]
I opened cen64-Qt and go to preferences>ROM Directories and find rom files in ROM folder. And it didn't showing up on cen64-Qt's list so I have to click OPEN ROM and find it and it's running ok. Why are ROMS not on cen64-Qt list ?

**Comment by Breadwinka** [comment]
This is a cen64-qt issue not cen64. cen64 itself is command line only, cen64-qt is a 3rd party front-end.

**Comment by azoreseuropa** [comment]
I'm aware of that. That's what I am saying in the above - Cen64-Qt and not Cen64 itself.

**Comment by Breadwinka** [comment]
Yes but then you should open the issue on their github https://github.com/dh4/cen64-qt

As this issue has nothing to do with the cen64,

**Comment by azoreseuropa** [comment]
Thank you kindly and I posted it there already but they are not alive since 3 months ago.

**Comment by tj90241** [comment]
As mentioned, this isn't an issue with CEN64, but rather a frontend... closing.
