### ISSUE TITLE
All-Star Baseball 2001 not starting

### ISSUE THREAD

**Issue by loganmc10** [tj90241/cen64#66]
It just sits at a white screen.

It may be related to this issue:

https://github.com/mupen64plus/mupen64plus-core/issues/221

(this game doesn't work in mupen64plus either, but works in Project64 and 1964)

**Comment by loganmc10** [comment]
If it is helpful, this is the error that is printed in mupen64plus, I'm only assuming the issue here is related:

```
tlb exception !!! @ 1004f8, 2, add:80000190
```

**Comment by loganmc10** [comment]
It also works in MAME N64. So Project64, 1964 and MAME have it working. Just not mupen64plus or cen64

**Comment by loganmc10** [comment]
All-Star Baseball 2000 and NFL Quarterback Club 99 have the same issue (all 3 games were done by the same developer)

**Comment by tj90241** [comment]
I beat up the TLB pretty hard in my test ROMs and couldn't get it to break too badly. I did find one such TLB bug, but fixed it. Without a debugger, it tends to be pretty hard to narrow down on problems.

**Comment by loganmc10** [comment]
Yeah it's probably not a problem with TLB (although I don't know for sure). I think it just has the wrong address so it's triggering a TLB exception. I don't know a ton about how this all works though.

**Comment by loganmc10** [comment]
I figured out what was the issue in mupen64plus https://github.com/mupen64plus/mupen64plus-core/pull/336

I'm not sure if the same applies to cen64 or if it's a different issue, just FYI
