### ISSUE TITLE
pifdata.bin error when loading rom

### ISSUE THREAD

**Issue by shoober420** [tj90241/cen64#75]
Everytime I try to load a ROM I get the following error.

Compiled error: Expected '(' on line 1 in /home/abc/pif/pifdata.bin

I've never used this emulator before. Is there something wrong with my settings? I do have the pifdata.bin file as well as the 64ddipl.bin file. I'm on Arch Linux 64bit using the latest git build.

**Comment by mikeryan** [comment]
Hi! You're using the wrong buildbot because @marathonm stubbornly refuses to link the one that people actually want to use. Please try builds from the following buildbot:

https://github-buildbot.cen64.com/

**Comment by shoober420** [comment]
Thank you sir
