### ISSUE TITLE
Doreamon error

### ISSUE THREAD

**Issue by tj90241** [tj90241/cen64#76]
![screenshot from 2017-07-16 21-22-51](https://user-images.githubusercontent.com/2336200/28253075-fe146522-6a6c-11e7-9a45-2f6ff470ccdf.png)

#n64dev discuss.

**Comment by queueRAM** [comment]
This is the error that you can see on console or other emulators when no controllers are plugged in.

![mupen64plus-gui_2018-01-11_20-55-58](https://user-images.githubusercontent.com/129774/34860411-0b2b4334-f712-11e7-86f0-11748264694d.png)

> コントローうー がゝ せつぞく されていま せん。
コネクター に せつぞく してからゝ
でんげん をいれなおしてください。

I'm not too familiar with Japanese, but after some translation services, I think it means

> The controller is not plugged in. Please connect the controller and reset the power.

I stepped through the code a little and have been able to determine that `osContInit` is at 0x8008bac0 and is called from 0x80001c9c. The third parameter to it is always 0x800e627a which is a pointer to an array of `OSContStatus` structures. If the error is set for all of them, the controller error message appears. I don't remember how to poke around in the RDRAM through gdb, so can't confirm the values seen in cen64.

**Comment by tj90241** [comment]
Meant to use the ROM database to store a temporary save file in RAM to bypass these issues, just never got around to it. There are also other games that refuse to boot - I believe *Mario Party 3* is another.
