### ISSUE TITLE
Immediate death after initial cutscene in Majora's Mask

### ISSUE THREAD

**Issue by sn0w75** [tj90241/cen64#80]
In Majora's Mask (USA version), if you start a new game, you immediately die after the initial cutscene, which should not happen.
After death, you respawn. Your sword and shield are missing (they should be there), and you have three ocarinas as your C-buttons (you should have nothing in those slots.)
I'm also pretty sure three hearts should be displayed in the top-left of the screen, but no hearts are displayed in this scene.

Here is a screenshot of the bug in action (after you've died/respawned).
![cen64 screenshot](https://i.imgur.com/PTnT2cf.png)

This bug occurred on Linux 64-bit, specifically the debian testing branch.
System is a AMD Threadripper 1950X with RX 580 GPU, using mesa open-source drivers (version 17.3.1, latest release at the time of writing.)

As an extra note that may be more difficult to investigate/confirm: It's hard to tell with the audio somewhat choppy, but I also think the echo effect in Skull Kid's laugh during the initial cutscene may not be reproduced correctly, either. (Reminds me of an old citra bug when playing Majora's Mask 3D earlier on in citra's development.)

**Comment by jkbenaim** [comment]
Hi @sn0w75 , I have good news for you.

You can fix the issue by using the ```-flash``` option on the command line. For example,
```cen64 -flash flash.bin pifdata.bin majora.z64```
It is not necessary for ```flash.bin``` to exist already. cen64 will create the file if it does not exist.

By the way: this seems to be the same as the 48 Ocarinas glitch, which you can read about [here](http://www.jaytheham.com/zcw/Majora's_Mask_Crooked_Cartridge_-_48_Ocarinas). It looks like quite an interesting way to play the game.

Hope this helped. Happy gaming!
![screenshot_20180106_204528](https://user-images.githubusercontent.com/2214896/34645743-49b4ca6e-f323-11e7-9a5d-e5af498d44c6.png)

**Comment by nopjne** [comment]
-flash does specify a file, however the flashram emulation seems to be incomplete or incorrect. After setting "flashram STATUS" for 2x, the game never attempts to put the flashram into read mode, after which neither erase or write happen at all for the entire duration of the game. This is the same as the absence of flashram, leading to the above 48 ocarina issue.
