### ISSUE TITLE
Not compiling with SSE4.1?

### ISSUE THREAD

**Issue by Qwertylex** [tj90241/cen64#83]
cen64 compiled with:  SSSE3
Your CPU supports:    SSE4.1
I compiled it on Linux 4.14.15-1-ARCH 
with gcc (GCC) 7.2.1 20180116
>mkdir build
>cmake ..
>make
>./cen64

>model name	: Intel(R) Core(TM) i7 CPU       Q 740  @ 1.73GHz
>flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti retpoline tpr_shadow vnmi flexpriority ept vpid dtherm ida

**Comment by tj90241** [comment]
I think it's due to a typo in the code that determines what it was compiled with:
https://github.com/tj90241/cen64/blob/master/cen64.c#L229

That should be __SSE4_1__, not __SSE41__.

The good news is, you're almost certainly running with the optimizations; it's just a reporting issue.

**Comment by Qwertylex** [comment]
Thanks!
