### ISSUE TITLE
Void-MUSL

### ISSUE THREAD

**Issue by johnny-mac** [tj90241/cen64#89]
Found your emulator today & got it working on my desktop compiled from source(running Devuan), but can't get it to compile on Void Linux MUSL unfortunately. What do you think I am missing?
https://pastebin.com/kwReaBqf

Also, on your debian binary packages(I think that's what they are supposed to be? they say debian on them) they don't have a .7z or a .deb or anything like that so my computer can't identify what it is, tried opening it with xarchiver but no luck.

**Comment by johnny-mac** [comment]
I removed #include <sys/cdefs.h> from /device/sha1.c on line 40(ish) & it successfully compiled!
But now, where do I get this PIF file thing? 

"PIF IPL file not found"

**Comment by J-128** [comment]
You're going to need to get that file yourself.  As part of the core N64 system, I don't think it can be legally provided by anyone else.  If you want to know what the PIF ROM does, you can read this [link to an article on en64.shoutwiki.com](http://en64.shoutwiki.com/wiki/N64_Memory#Boot_Strap).  It explains it better than I could.

**Comment by kenny-w1** [comment]
Well I have a nintendo 64 back at my parents house, still not sure how I'm supposed to get the PIF file though :/

**Comment by johnny-mac** [comment]
Telling me its no different than PS1 emulators still doesn't tell me HOW I rip one of these things from a N64... I have found pif .dat files, but not pif .bin files...

**Comment by johnny-mac** [comment]
I'm looking everywhere trying to find one of these PIF .bin files but I just can't seem to find one... I downloaded the MESS bios collection but there's no n64 one there either :/

**Comment by johnny-mac** [comment]
I re-cloned & re-compiled cen64, its now no longer getting the error about sys/cdefs.h 
odd since last commit was feb 25th...  Was something changed so that it wouldn't come up as an error on MUSL?

**Comment by johnny-mac** [comment]
All of the PIF files I try do not work... Still haven't been able to get it working.

**Comment by johnny-mac** [comment]
I'm not quite sure but I think cen64 doesn't work with MUSL, at least not for me anyway. 
If anyone else reports differently I would be interested to know how they did it.

**Comment by AriaHiro** [comment]
its the same bios as mame if you really need the help
