### ISSUE TITLE
Minor shading inaccuracies in PAL Mario Kart 64

### ISSUE THREAD

**Issue by Nabile-Rahmani** [tj90241/cen64#90]
The flag at the title screen and the victory balloon are darker than on real hardware.

## Output from my console

![image](https://user-images.githubusercontent.com/15223353/38780654-7072b0d0-40da-11e8-8de6-01499ac6e0c7.png)
[Video](https://nabile.s-ul.eu/VHTmuNBi.mp4)

## Output from CEN (master and stable)
![image](https://user-images.githubusercontent.com/15223353/38780664-8d6c5448-40da-11e8-8d53-9279275a1a8d.png)
[Video](https://nabile.s-ul.eu/FNSJ45F7.mp4)

Looks like the refresh rate isn't capped at 50 Hz either, so the music is sped up at one point.

**Comment by LegendOfDragoon** [comment]
probaaby RSP related

**Comment by PeterLemon** [comment]
This is a known problem, LTV/STV RSP opcodes are not implemented atm in cen64.
These opcodes are used for transposing a matrix, & are used in the lighting ucodes of the N64.
