### ISSUE TITLE
Cant open cen64 on Windows anymore.

### ISSUE THREAD

**Issue by ProjectRevoTPP** [tj90241/cen64#93]
<img width="510" alt="untitled" src="https://user-images.githubusercontent.com/11638236/39677202-eeec4d52-5144-11e8-87b5-b82371366eb6.png">

Downloaded cen64 as of today and realized I couldn't open it.

OS: Windows 10
CPU: i7-4770K

I should have AVX support, so I don't know what went wrong here.

**Comment by ProjectRevoTPP** [comment]
Okay, looks like buildbot is broken. Its generating windows EXEs that are 0 bytes in size, so thats why I can't run it. I guess I didn't notice.

**Comment by tlercher** [comment]
@ProjectRevoTPP should be fixed

**Comment by PeterLemon** [comment]
Confirmed fixed, binary is available on cen64.com website =D
